# Generated by Django 5.2.7 on 2025-10-19 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=50)),
                ("intent_id", models.CharField(db_index=True, max_length=64)),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="IRR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("provider_ref", models.CharField(blank=True, max_length=128, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("provider_refund_id", models.CharField(blank=True, max_length=128, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "payment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="billing.payment"),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
        migrations.CreateModel(
            name="ProviderTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("init", "Init"),
                            ("redirect", "Redirect"),
                            ("callback", "Callback"),
                            ("verify_ok", "Verify success"),
                            ("verify_fail", "Verify failed"),
                            ("consumed", "Consumed"),
                            ("refund_requested", "Refund requested"),
                            ("refund_succeeded", "Refund succeeded"),
                            ("refund_failed", "Refund failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("ts", models.DateTimeField(default=timezone.now)),
                (
                    "payment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="billing.payment"),
                ),
            ],
            options={
                "ordering": ("-ts",),
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("payment_create", "Payment create"),
                            ("payment_verify", "Payment verify"),
                            ("refund", "Refund"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="idempotency_keys", to="billing.payment"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["provider", "provider_ref"], name="billing_pay_provider_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["intent_id"], name="billing_pay_intent_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "created_at"], name="billing_pay_status_created_ix"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="success"),
                fields=("intent_id",),
                name="unique_success_payment_per_intent",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(provider_ref__isnull=False),
                fields=("provider", "provider_ref"),
                name="unique_provider_ref",
            ),
        ),
    ]
