# Generated by Django 5.2.7 on 2025-10-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_wallet'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='billing_wal_wallet__2827cc_idx',
            old_name='billing_wallet_tx_idx',
        ),
    ]
