# Generated by Django 5.2.7 on 2025-10-20 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_child"),
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("lang", models.CharField(default="fa", max_length=5)),
                ("reading_level", models.CharField(default="k1", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="READY",
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("hidden_reason", models.TextField(blank=True, null=True)),
                ("plan_source", models.CharField(default="free", max_length=8)),
                ("cover_url", models.URLField(blank=True, null=True)),
                ("cover_meta", models.JSONField(blank=True, default=dict)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stories",
                        to="accounts.child",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story",
                        to="requests.storyrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_no", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("voice_url", models.URLField(blank=True, null=True)),
                ("timings_json", models.JSONField(blank=True, default=dict)),
                ("annotations_json", models.JSONField(blank=True, default=dict)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ("page_no",),
            },
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["status", "visibility", "is_hidden", "lang"],
                name="story_status_visibility_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["owner", "status"], name="story_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["slug"], name="story_slug_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="scene",
            unique_together={("story", "page_no")},
        ),
    ]
