# Generated by Django 5.2.7 on 2025-10-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_storyproduct_bazaar_sku'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storyproduct',
            new_name='stories_sto_is_acti_ebed17_idx',
            old_name='stories_storyproduct_active_order_idx',
        ),
    ]
