# Generated by Django 5.2.7 on 2025-10-19 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_child"),
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lang", models.CharField(default="fa", max_length=5)),
                (
                    "reading_level",
                    models.CharField(
                        choices=[
                            ("k1", "Kindergarten 1"),
                            ("k2", "Kindergarten 2"),
                            ("k3", "Kindergarten 3"),
                            ("g1", "Grade 1"),
                            ("g2", "Grade 2"),
                        ],
                        default="k1",
                        max_length=3,
                    ),
                ),
                ("theme", models.CharField(max_length=200)),
                ("prompt_note", models.TextField(blank=True)),
                ("characters_json", models.JSONField(default=list)),
                (
                    "plan",
                    models.CharField(choices=[("free", "Free"), ("paid", "Paid")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("PAYMENT_REQUIRED", "Payment required"),
                            ("QUEUED_FREE", "Queued (free)"),
                            ("QUEUED_PAID", "Queued (paid)"),
                            ("IN_PROGRESS", "In progress"),
                            ("REVIEW_PENDING", "Review pending"),
                            ("READY_FOR_USER", "Ready for user"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("queue_priority", models.IntegerField(default=100)),
                ("position_hint", models.PositiveIntegerField(default=0)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="story_requests",
                        to="accounts.child",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="story_requests",
                        to="billing.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("queue_priority", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="RequestTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("PAYMENT_REQUIRED", "Payment required"),
                            ("QUEUED_FREE", "Queued (free)"),
                            ("QUEUED_PAID", "Queued (paid)"),
                            ("IN_PROGRESS", "In progress"),
                            ("REVIEW_PENDING", "Review pending"),
                            ("READY_FOR_USER", "Ready for user"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("PAYMENT_REQUIRED", "Payment required"),
                            ("QUEUED_FREE", "Queued (free)"),
                            ("QUEUED_PAID", "Queued (paid)"),
                            ("IN_PROGRESS", "In progress"),
                            ("REVIEW_PENDING", "Review pending"),
                            ("READY_FOR_USER", "Ready for user"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="story_request_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="requests.storyrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="storyrequest",
            index=models.Index(
                fields=["status", "queue_priority", "created_at"],
                name="requests_st_status_00ff80_idx",
            ),
        ),
    ]
