# Generated by Django 5.2.7 on 2025-10-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('stories', '0004_rename_stories_storyproduct_active_order_idx_stories_sto_is_acti_ebed17_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_requests', to='stories.storyproduct'),
        ),
    ]
